### ISSUE TITLE
Odd prints, likely my configuration

### ISSUE THREAD

**Issue by ypearson** [charlesnicholson/nanoprintf#230]
Prints out
```
abc
abc=536875404
abc=2000118c
```

From
```
printfx_("abc\r\n");
printfx_("abc=%d\r\n",5);
printfx_("abc=%x\r\n",50);
```

Code
```
#define NANOPRINTF_USE_FIELD_WIDTH_FORMAT_SPECIFIERS 1
#define NANOPRINTF_USE_PRECISION_FORMAT_SPECIFIERS 1
#define NANOPRINTF_USE_LARGE_FORMAT_SPECIFIERS 1
#define NANOPRINTF_USE_FLOAT_FORMAT_SPECIFIERS 1
#define NANOPRINTF_USE_BINARY_FORMAT_SPECIFIERS 1
#define NANOPRINTF_USE_WRITEBACK_FORMAT_SPECIFIERS 1

// Compile nanoprintf in this translation unit.
#define NANOPRINTF_IMPLEMENTATION

#include "External/nanoprintf-0.3.2/nanoprintf.h"

void putchar_(char c, void *ctx) {
    char data[] = {c};
    SERCOM3_USART_Write((void*)data, 1);
}

void printf_(char const *fmt, ...) {
    va_list args;
    va_start(args, fmt);
    npf_pprintf(putchar_, NULL, fmt, args);
    va_end(args);
}
uint8_t buffer[128];

void printfx_(char const *fmt, ...) {
    va_list args;
    va_start(args, fmt);
    int len = npf_snprintf(buffer, 128, fmt, args);
    va_end(args);
    for(int i = 0; i < len; i++) {
        putchar_(buffer[i], NULL);
    }
}
```

Is my setup wrong here? thx

**Comment by charlesnicholson** [comment]
Interesting, I wonder if it has to do with how your terminal handles carriage returns.

As an experiment, what happens when you simply print this instead? (i.e. without the `\r` characters?)

```
printfx_("abc\n");
printfx_("abc=%d\n",5);
printfx_("abc=%x\n",50);
```

**Comment by charlesnicholson** [comment]
I think it might be your `putchar_` function:
```
void putchar_(char c, void *ctx) {
    char data[] = {c};
    SERCOM3_USART_Write((void*)data, 1);
}
```

What happens when you replace it with this:
```
void putchar_(char c, void *ctx) {
    SERCOM3_USART_Write(&c, 1);
}
```

**Comment by ypearson** [comment]
> 

Same result

**Comment by charlesnicholson** [comment]
oh interesting, i wonder if it's a race condition, i'm looking at 

what happens when you do this?

```
void putchar_(char c, void *ctx) {
    SERCOM3_USART_Write(&c, 1);
    while (SERCOM3_USART_WriteIsBusy()) {}
}
```

Looking at the [implementation](SERCOM3_USART_WriteIsBusy) of `SERCOM3_USART_Write`, it just caches the buffer pointer. Since the "buffer" here is a stack variable, who knows what's actually getting written out :)

**Comment by charlesnicholson** [comment]
Either way, `2000118c` is a clue; i'm guessing that your RAM section starts at `0x20000000` so it looks to be printing an address instead of the value at that address...

Do you have the ability to inspect the contents of your 128-byte `buffer` variable in a debugger? It would be interesting to learn if nanoprintf is actually shoving garbage in there, or if it's being correctly formatted and having trouble going through the USART...

**Comment by ypearson** [comment]
I don't think its the putchar function since I've been using Eyal's version without issue. The version of the call is blocking, so that should be ok.
 I'll try to poke around some more...

**Comment by ypearson** [comment]
This is funny
```
int x{5};
printfx_("abc=%x\r\n",x);
printfx_("abc=%x\r\n",&x);
```
prints
```
abc=20001184
abc=20001184
```

**Comment by charlesnicholson** [comment]
oh, hahaha, sorry I missed this originally-

Since you're extracting the variadic arguments into a `va_list` yourself, you need to call the `v` flavors of nanoprintf. As it is currently, you're passing the va_args struct in to npf and it's pulling it out as an unsigned or hex. :) That explains why it's a stack value too :)

You probably want something like this (note the `npf_v` calls):

```
void printf_(char const *fmt, ...) {
    va_list args;
    va_start(args, fmt);
    npf_vpprintf(putchar_, NULL, fmt, args);
    va_end(args);
}
uint8_t buffer[128];

void printfx_(char const *fmt, ...) {
    va_list args;
    va_start(args, fmt);
    int len = npf_vsnprintf(buffer, 128, fmt, args);
    va_end(args);
    for(int i = 0; i < len; i++) {
        putchar_(buffer[i], NULL);
    }
}
```

**Comment by ypearson** [comment]
Bingo, thank you. You're awesome

**Comment by charlesnicholson** [comment]
Glad I could help! Enjoy nanoprintf :)
