### ISSUE TITLE
Define Guard: error multiple definition npf_vpprintf, npf_pprintf, npf_snprintf,npf_vsnprintf

### ISSUE THREAD

**Issue by andkae** [charlesnicholson/nanoprintf#242]
Hi Charles,

at the moment i try to inculde the nanoptintf.h into several files, they are also included. Following example:

* main.c
    * ```#include "nanoprintf.h"``` 
    * ```#include "sub.h" ```
        *  ```#include "nanoprintf.h"``` 

There i receive the compiler errors of multiple definition of ```npf_vpprintf, npf_pprintf, npf_snprintf,npf_vsnprintf```. In your code it looks like an define guard, but i have no idea why i receive this eros.

```bash
./include/nanoprintf/nanoprintf.h:1045: multiple definition of `npf_vsnprintf'; ./main.c.o:./include/nanoprintf/nanoprintf.h:1045: first defined here
```

Thanks for your help.

BR,
Andreas

**Comment by charlesnicholson** [comment]
Hello- this looks like a linker error, which makes me think that you maybe have

```
#define NANOPRINTF_IMPLEMENTATION
```

specified in more than one place. If you're just #include-ing "nanoprintf.h" to get the API function prototypes, you don't need any macro definitions beforehand. Usually you just want to `#include "nanoprintf.h"` without any define flags above it, for files that just want to call it.

Alternately, maybe your build system passes `-DNANOPRINTF_IMPLEMENTATION` into the compiler for every file or something like that?

As an example, https://github.com/charlesnicholson/nanoprintf/blob/main/examples/use_npf_directly/your_project_nanoprintf.cc has code that should only be used in one single file in your entire project, that tells the nanoprintf header file to throw the entire implementation directly into that c or cc file.

But, when you're just _calling_ into nanoprintf, you want something more like this: https://github.com/charlesnicholson/nanoprintf/blob/main/examples/use_npf_directly/main.cc where there are no `#define` directives before the `#include` statement.

Could you share any of your code, so that I can see how you're trying to include and use nanoprintf?

**Comment by charlesnicholson** [comment]
By the way, as an aside, I was actually worried about what you describe, so a while back I added a test that `#include`'s nanoprintf a bunch of times in the same file :)

https://github.com/charlesnicholson/nanoprintf/blob/main/tests/include_multiple.c

**Comment by charlesnicholson** [comment]
ohhhhh i think i maybe understand what's happening-

if you do something like this:

foo.h:
```
#define NANOPRINTF_IMPLEMENTATION
#include "nanoprintf.h"
#include "bar.h"
```

bar.h:
```
#include "nanoprintf.h"
```

Then you're telling nanoprintf to expand its implementation twice. You'll have to change foo.h to this:
```
#define NANOPRINTF_IMPLEMENTATION
#include "nanoprintf.h"
#undef NANOPRINTF_IMPLEMENTATION
#include "bar.h"
```

**Comment by andkae** [comment]
Hi Charles,

yes good hint :). Thanks for your help.

I removed ```NANOPRINTF_IMPLEMENTATION``` from makefile and added it to the files. Now all works fine. In General the #def, #undef thing needs then to take place in the highest level file?

BR,
Andreas

**Comment by charlesnicholson** [comment]
I think a best practice for using nanoprintf is to only `#define NANOPRINTF_IMPLEMENTATION` in one file that only includes nanoprintf.h once and only once.

So in your case, I would probably just make a standalone .c file that looked like this:
https://github.com/charlesnicholson/nanoprintf/blob/main/examples/use_npf_directly/your_project_nanoprintf.cc

Don't add any other code in there, just use that C/C++ file as a place to compile the nanoprintf implementation. Don't `#define NANOPRINTF_IMPLEMENTATION` anywhere else in your codebase, just in that one C/C++ file. Maybe even name that file `nanoprintf.c` or something :)

Then, in any other .c or .h file, if you want to be able to call the nanoprintf functions, just `#include "nanoprintf.h"` without defining any other nanoprintf-related flags.

That's probably the easiest way to configure and use nanoprintf, I think.

**Comment by charlesnicholson** [comment]
For your case I suggested the `#undef NANOPRINTF_IMPLEMENTATION` because that was an easy way to fix the setup you described, but I wouldn't recommend using the setup as you've described it. :)

**Comment by charlesnicholson** [comment]
Anyway, LMK if this makes sense, and feel free to close the issue if so!

**Comment by andkae** [comment]
Hi Charles,

sounds valid and suitable for me. Thanks for your help!

BR,
Andreas
