### ISSUE TITLE
Clang address/undefined behaviour sanitizer errors

### ISSUE THREAD

**Issue by shreyasbharath** [charlesnicholson/nanoprintf#75]
Thanks for creating a great library!

Was running into a couple of errors when compiled with Clang's address/undefined behaviour sanitizers. A couple of examples below -

```
nanoprintf.h:893:57: runtime error: load of value 18036456, which is not a valid value for type 'npf__format_spec_conversion_case_t'

nanoprintf.h:555:14: runtime error: load of value 18036456, which is not a valid value for type 'npf__format_spec_conversion_case_t'
```

These are not controlled by the user directly so I presume it's some sort of initialisation error in the library?

**Comment by charlesnicholson** [comment]
Sorry for the delay, I seem to have somehow disabled notifications and only see issues + PRs when I poll for them.

That's odd and fun, do you have a repro case? I'd love to figure out how to fix it + harness it in CI...

**Comment by charlesnicholson** [comment]
I think the original code was safe because the variable was only used if the supplied digit was > 9, but yikes it was tiptoeing the line and clang was right to yell at me :)

Anyway, the variable is now always initialized, which actually golfed 6 bytes off the cortex-m0 binary since there are fewer assignments overall haha
